swagger: '2.0'
info:
  version: '1.0.0'
  title: StepFlow Events Source Handler
host: stepflow.fixme
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /events:
    post:
      operationId: addEvents
      parameters:
        - name: events
          in: body
          description: A events.
          required: true
          schema:
            $ref: '#/definitions/events'
      responses:
        '201':
          description: events inserted
definitions:
  events:
    type: array
    items:
      type: object
      required:
        - body
      properties:
        headers:
          type: object
        body:
          type: object
